### ISSUE TITLE
Too many arguments to if, compiling:(grunf/core.clj:31:5)

### ISSUE THREAD

**Issue by alek** [Supplyframe/grunf#19]
unknown14109fe1bf15:grunf alek$ lein trampoline run -c conf.example.clj
Exception in thread "main" java.lang.RuntimeException: Too many arguments to if, compiling:(grunf/core.clj:31:5)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6567)
    at clojure.lang.Compiler.analyze(Compiler.java:6361)
    at clojure.lang.Compiler.analyze(Compiler.java:6322)
    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5708)
    at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6009)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6560)

**Comment by dryman** [comment]
Fixed
