### ISSUE TITLE
Failed when graphite socket is closed

### ISSUE THREAD

**Issue by dryman** [Supplyframe/grunf#22]
```
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:391)
    at java.net.Socket.connect(Socket.java:579)
    at java.net.Socket.connect(Socket.java:528)
    at java.net.Socket.<init>(Socket.java:425)
    at java.net.Socket.<init>(Socket.java:208)
    at grunf.core$eval413$fn__415.invoke(core.clj:34)
```

**Comment by dryman** [comment]
In v0.25, unless --graphite-host is on, won't connect to graphite
Still need to handle socket exception though
