### ISSUE TITLE
add user-friendly comments when reporting exeptions

### ISSUE THREAD

**Issue by alek** [Supplyframe/grunf#34]
example : 

java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
        at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
        at java.net.Socket.connect(Socket.java:529)

(actual error is connection error on graphite host - but there's nothing in log to indicate that so it's a challenge to debug)

**Comment by dryman** [comment]
SMTP and Graphite socket exceptions are handled
