### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by dryman** [Supplyframe/grunf#43]
```
java.lang.OutOfMemoryError: Java heap space, compiling:(NO_SOURCE_PATH:26:31)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6567)
        at clojure.lang.Compiler.analyze(Compiler.java:6361)
        at clojure.lang.Compiler.eval(Compiler.java:6616)
        at clojure.lang.Compiler.eval(Compiler.java:6582)
        at clojure.core$eval.invoke(core.clj:2852)
        at grunf.core$fetch.invoke(core.clj:54)
        at grunf.bin$_main$fn__1700.invoke(bin.clj:132)
        at clojure.lang.AFn.run(AFn.java:24)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

Probably because of `(eval validator)`

**Comment by dryman** [comment]
fixed in eae7d9b
